var modules =
[
    [ "ACCEL module documentation", "group___a_c_c_e_l__module.html", "group___a_c_c_e_l__module" ],
    [ "Events module documentation", "group___events__module.html", null ],
    [ "FIFO module documentation", "group___f_i_f_o__module.html", "group___f_i_f_o__module" ],
    [ "Flash module documentation", "group___flash__module.html", "group___flash__module" ],
    [ "FTM module documentation", "group___f_t_m__module.html", "group___f_t_m__module" ],
    [ "I2C module documentation", "group___i2_c__module.html", "group___i2_c__module" ],
    [ "LED module documentation", "group___l_e_d__module.html", "group___l_e_d__module" ],
    [ "main module documentation", "group__main__module.html", "group__main__module" ],
    [ "I2C module documentation", "group___median__module.html", "group___median__module" ],
    [ "Packet module documentation", "group___packet__module.html", "group___packet__module" ],
    [ "PIT module documentation", "group___p_i_t__module.html", "group___p_i_t__module" ],
    [ "RTC module documentation", "group___r_t_c__module.html", "group___r_t_c__module" ],
    [ "Packet module documentation", "group___types__module.html", "group___types__module" ],
    [ "UART module documentation", "group___u_a_r_t__module.html", "group___u_a_r_t__module" ],
    [ "Cpu module documentation", "group___cpu__module.html", "group___cpu__module" ],
    [ "PE_Const module documentation", "group___p_e___const__module.html", "group___p_e___const__module" ],
    [ "PE_Error module documentation", "group___p_e___error__module.html", "group___p_e___error__module" ],
    [ "PE_LDD module documentation", "group___p_e___l_d_d__module.html", "group___p_e___l_d_d__module" ],
    [ "PE_Types module documentation", "group___p_e___types__module.html", "group___p_e___types__module" ],
    [ "Vectors module documentation", "group___vectors__module.html", null ],
    [ "Interrupt vector numbers", "group___interrupt__vector__numbers.html", "group___interrupt__vector__numbers" ],
    [ "Peripheral type defines", "group___peripheral__defines.html", "group___peripheral__defines" ],
    [ "Backward Compatibility", "group___backward___compatibility___symbols.html", null ]
];